### PR TITLE
Support for browserify

### PR DESCRIPTION
**Pull request by CJNE**
Browserify looks for a main property, use the src file to avoid webpack problems.
Nice module :)

### CODE REVIEW

**Comment by mattlewis92** [comment]
Hi thanks for the PR! This module should already be compatible with both webpack and browserify as they both use the `browser` field which is already defined [here](https://github.com/mattlewis92/angular-bluebird-promises/blob/master/package.json#L5). The dist file is used instead of the source as it is pre-annotated and also compatible with commonjs as it is exported as UMD. Discussion on that [here](https://github.com/mattlewis92/angular-bluebird-promises/pull/10).

**Comment by CJNE** [comment]
Hi,

I have installed this module using npm and i'm using https://github.com/substack/node-resolve to resolve dependencies in my build step and it will only look for the main property.

The pre-annotated version does not work with browserify, at least not in my project. It errors on angular.extend (not defined).
The source file works perfectly fine though.

**Comment by mattlewis92** [comment]
Sorry I'm a bit confused, are you using browserify or just the node-resolve library? If using browserify `require('angular-bluebird-promises')` should just work.

**Comment by CJNE** [comment]
I should explain better :)
I'm using gulp to generate my browserify bundles, splitting them up into a vendor bundle for third-party code and a separate bundle for my app.
```javascript
function buildVendor() {
  // this task will go through ./bower.json and
  // uses bower-resolve to resolve its full path.
  // the full path will then be added to the bundle using require()

  var b = browserify({
    // generate source maps in non-production environment
    debug: false //!production
  });
  gutil.log("Build vendor");
  b.on('log', function(msg) { gutil.log("Bundling vendor done "+msg)});
  b.on('bundle', function(ids) {
    gutil.log("Vendor bundle");
  });

  // get all bower components ids and use 'bower-resolve' to resolve
  // the ids to their full path, which we need for require()
  getBowerPackageIds().forEach(function (id) {

    var resolvedPath = bowerResolve.fastReadSync(id);

    b.require(resolvedPath, {

      // exposes the package id, so that we can require() from our code.
      // for eg:
      // require('./vendor/angular/angular.js', {expose: 'angular'}) enables require('angular');
      // for more information: https://github.com/substack/node-browserify#brequirefile-opts
      expose: id

    });
  });

  // do the similar thing, but for npm-managed modules.
  // resolve path using 'resolve' module
  
  getNPMPackageIds().forEach(function (id) {
    if(id == 'simsfiles') {
      //b.require('simsfiles', { expose: id });
      //Skip simsfiles
    }
    else b.require(nodeResolve.sync(id), { expose: id });
  });
  

  var stream = b.bundle().pipe(source('vendor.js'));

  // pipe additional tasks here (for eg: minifying / uglifying, etc)
  // remember to turn off name-mangling if needed when uglifying

  stream.pipe(gulp.dest('./app/public/dist'));

  return stream;
}

function getBowerPackageIds() {
  // read bower.json and get dependencies' package ids
  var bowerManifest = {};
  try {
    bowerManifest = require('./bower.json');
  } catch (e) {
    // does not have a bower.json manifest
  }
  return _.keys(bowerManifest.buildDependencies) || [];
}


function getNPMPackageIds() {
  // read package.json and get dependencies' package ids
  var packageManifest = {};
  try {
    packageManifest = require('./package.json');
  } catch (e) {
    // does not have a package.json manifest
  }
  return _.keys(packageManifest.browserDependencies) || [];
}
```
For this to work the `main` property needs to be set otherwise node-resolve will not find the file.

Why the annoted dist file doesn't work for me might be a separate issue, but there is no need for the annotation when using browserify.

**Comment by mattlewis92** [comment]
Hey sorry about the late reply, I believe swapping `node-resolve` for [this module](https://www.npmjs.com/package/browser-resolve) instead should solve your problem. It should just be a drop in replacement and will work for other modules that rely on the browser field :smile: 

On a bit of a sidenote, have you tried webpack as an alternative to browserify? If you're already using commonjs it should be easy enough to transition and you can usually remove complicated gulpfiles and replace them with a simple webpack config. [This plugin](https://github.com/soundcloud/split-by-name-webpack-plugin) for example would be great for your needs.

**Comment by CJNE** [comment]
Hello Matt,

I did not know about that module, i just tried it and it worked perfectly :)
Thanks a lot for assisting me!

I am considering webpack, problem is that some parts of the app actually
require node stuff.
One option could be to only use browserify for that part and webpack for
the rest, the plugin you linked to looked great for splitting the rest up
in vendor and app bundles.

Thanks again for the help and for providing this module, great idea :)

Regards,
Johan Isacsson

2015-10-15 23:04 GMT+02:00 Matt Lewis <notifications@github.com>:

**Pull request closed without merging**
