### PR TITLE
module.exports fixed

### PR DESCRIPTION
**Pull request by CristianMR**
I've been used this library in my app a long time ago. At the last days, I found a problem using the library braintree-web, and figured out the problem inside this library. So, I wish to help another people to prevent the problem.

Greetings

### CODE REVIEW

**Comment by mattlewis92** [comment]
Sorry I don't quite get what your problem is, I don't see why exporting the module name as an array would fix anything, in fact I only see this breaking things for everyone else. I'm guessing you're consuming this with browserify / webpack? Could you explain a little bit more what this is meant to fix?

**Comment by CristianMR** [comment]
Yes, of course.

Imagine a little variation of the code, just with some console.logs
```javascript
var a = typeof exports === 'object' ? factory(require("angular"), require("bluebird"));
factory(root["angular"], root["Promise"]);
console.log('a ', a);
for(var i in a) {
  console.log('a['+i+']', a[i]);
  (typeof exports === 'object' ? exports : root)[i] = a[i];
}
```
When I run that code, 'a' is an string and the output look like this:
```
a  mwl.bluebird
a[0] m
a[1] w
a[2] l
a[3] .
a[4] b
a[5] l
a[6] u
a[7] e
a[8] b
a[9] i
a[10] r
a[11] d
```
Before see that all the code zone is generated by webpack, I though something like put a condition and verify if the 'var a' was and string, but I don't see that possible because the code is auto generated. And because braintree-web use some sort of module system, somehow is breaking the expected behaviour of the library.

**Comment by mattlewis92** [comment]
Ah right, I see what's going on now, thanks for explaining that! I've done some digging and there is a better fix that won't break commonjs. It's late here now but I will push it out early tomorrow. Thanks for reporting this, it's been really helpful! :smile:

**Comment by CristianMR** [comment]
Thanks to you ! Is the first time seeing a code with webpack, so that was the best I could figure out in the last hours. Happy weekend my friend !

**Comment by mattlewis92** [comment]
0.5.6 is released which should solve your problem :smile: Have a good weekend!

**Pull request closed without merging**
