### PR TITLE
Fixing angular dependencies

### PR DESCRIPTION
**Pull request by lucastschmidt**
I tried to minify my code and encounter issue, since the dependencies were not declared.

### CODE REVIEW

**Comment by mattlewis92** [comment]
Are you installing from npm by any chance?

**Comment by mattlewis92** [comment]
If you're installing from npm the package main file now correctly points to the dist file which contains the pre-annotated code.

However if installing from bower then just use the pre-annotated dist file, and I've excluded the src folder from being available now which should clear up any confusion.

**Comment by lucastschmidt** [comment]
@mattlewis92 ok thanks. I was installing with npm, using browserify.

**Comment by mattlewis92** [comment]
Thought that might be the case, if you update to the latest version you should be good to go! :)

**Pull request closed without merging**
